{% set name = "segment-analytics-python" %}
{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/segment_analytics_python-{{ version }}.tar.gz
  sha256: f188e864cc0fed9fb141aff73c21bfaab783a1dd1b97ab1eff44340aed68f50b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - requests >=2.7,<3.0
    - backoff >=2.1,<3.0
    - python-dateutil >=2.2,<3.0
    - pyjwt >=2.10.1,<2.11.0

test:
  source_files:
    - segment/analytics/test
  imports:
    - segment.analytics
  commands:
    - pip check
    - pytest segment/analytics/test -v
  requires:
    - python
    - pip
    - pytest
    - mock
    - pylint
    - flake8
    - cryptography

about:
  home: https://github.com/segmentio/analytics-python
  summary: The hassle-free way to integrate analytics into any python application.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/segmentio/analytics-python
  doc_url: https://github.com/segmentio/analytics-python/blob/master/README.md

extra:
  recipe-maintainers:
    - xylar
